"""Optional sheets: Assumptions (always), Treatment Costing, Container Freight, Market Size."""

from __future__ import annotations

from openpyxl import Workbook

from .. import model
from ..schema import Plan
from .inputs import MARKET_COLS, MARKET_SHEET, SETTINGS_ROWS, InputRefs
from .price import Expected, SkuRefs
from .style import BOLD, IDR, MONEY, PCT, SUBTITLE, SUBTOTAL_FILL, TITLE, TOP_RULE, WRAP, header_row, widths

ASSUMPTIONS_SHEET = "Assumptions"
TREATMENT_SHEET = "Treatment Costing"
FREIGHT_SHEET = "Container Freight"
MARKET_OUT_SHEET = "Market Size"


def write_assumptions(wb: Workbook, plan: Plan, refs: InputRefs, modules: list[str]) -> None:
    ws = wb.create_sheet(ASSUMPTIONS_SHEET)
    ws.cell(1, 2, f"{plan.settings.brand} – business plan assumptions").font = TITLE
    ws.cell(2, 2, "Generated by the KNS business plan generator. Change inputs on the '_Inputs' sheets "
                  "(or in the app) — output sheets are rebuilt on every generate.").font = SUBTITLE
    header_row(ws, 4, ["Setting", "Value"], start_col=2)
    fmts = {"fx_rate": MONEY, "vat_rate": PCT, "rounding_step": IDR, "stock_cover_months": "0.0"}
    for i, (key, desc, _) in enumerate(SETTINGS_ROWS, start=5):
        ws.cell(i, 2, desc)
        c = ws.cell(i, 3, f"={refs.settings[key]}")
        if key in fmts:
            c.number_format = fmts[key]
    r = 6 + len(SETTINGS_ROWS)
    ws.cell(r, 2, "Sheets in this workbook").font = BOLD
    for i, name in enumerate(modules, start=1):
        ws.cell(r + i, 2, name)
    widths(ws, {"A": 2, "B": 58, "C": 22})


def write_treatments(wb: Workbook, plan: Plan, refs: InputRefs, skus: dict[str, SkuRefs],
                     expected: list[Expected]) -> None:
    ws = wb.create_sheet(TREATMENT_SHEET)
    ws.cell(1, 2, "Treatment costing").font = TITLE
    ws.cell(2, 2, "Cost per treatment = Σ usage ÷ product size × product forecast price. "
                  "Suggested outlet price = cost × multiplier.").font = SUBTITLE
    heads = ["Product", "Usage per treatment", "Product size", "Share of one unit", "Forecast price (IDR)",
             "Cost per treatment (IDR)"]
    row = 4
    for p in plan.packages:
        ws.cell(row, 2, p.name + (f" ({p.duration_minutes} min)" if p.duration_minutes else "")).font = BOLD
        row += 1
        header_row(ws, row, heads, start_col=2)
        row += 1
        first = row
        for comp in p.components:
            sr = refs.skus[comp.sku]
            ws.cell(row, 2, f"={skus[comp.sku].name}")
            ws.cell(row, 3, f"={refs.package_usage[(p.id, comp.sku)]}").number_format = "0.00"
            ws.cell(row, 4, f'=IF({sr["size"]}="",1,{sr["size"]})').number_format = "0.00"
            ws.cell(row, 5, f"=C{row}/D{row}").number_format = "0.0000"
            ws.cell(row, 6, f"={skus[comp.sku].forecast_price}").number_format = IDR
            ws.cell(row, 7, f"=E{row}*F{row}").number_format = IDR
            row += 1
        ws.cell(row, 2, "Product cost per treatment").font = BOLD
        c = ws.cell(row, 7, f"=SUM(G{first}:G{row - 1})")
        c.number_format, c.font, c.border = IDR, BOLD, TOP_RULE
        expected.append(Expected(TREATMENT_SHEET, f"G{row}", model.treatment_cost(plan, p.id), f"cost of {p.id}"))
        ws.cell(row + 1, 2, "Price multiplier")
        ws.cell(row + 1, 7, f"={refs.packages[p.id]['multiplier']}").number_format = "0.00"
        ws.cell(row + 2, 2, "Suggested outlet price per treatment").font = BOLD
        c = ws.cell(row + 2, 7, f"=G{row}*G{row + 1}")
        c.number_format, c.font, c.fill = IDR, BOLD, SUBTOTAL_FILL
        row += 5
    widths(ws, {"A": 2, "B": 42, "C": 18, "D": 13, "E": 15, "F": 18, "G": 22})


def write_freight(wb: Workbook, plan: Plan, refs: InputRefs, skus: dict[str, SkuRefs],
                  expected: list[Expected]) -> None:
    ws = wb.create_sheet(FREIGHT_SHEET)
    cur = plan.settings.brand_currency
    ws.cell(1, 2, "Container freight").font = TITLE
    ws.cell(2, 2, "Freight share = container cost ÷ (units per container × average brand price). Use it as a "
                  "starting point for the freight line of the cost stack.").font = SUBTITLE
    fobs = ",".join(s.cost_fob for s in skus.values())
    ws.cell(4, 2, f"Average brand price across products ({cur})")
    ws.cell(4, 3, f"=AVERAGE({fobs})").number_format = MONEY
    header_row(ws, 6, ["Container", f"Cost ({cur})", "Units", f"Goods value ({cur})", "Freight share"], start_col=2)
    for i, (opt, cr) in enumerate(zip(plan.containers, refs.containers)):
        r = 7 + i
        ws.cell(r, 2, f"={cr['name']}")
        ws.cell(r, 3, f"={cr['cost']}").number_format = MONEY
        ws.cell(r, 4, f"={cr['units']}").number_format = "#,##0"
        ws.cell(r, 5, f"=D{r}*$C$4").number_format = MONEY
        c = ws.cell(r, 6, f"=C{r}/E{r}")
        c.number_format, c.font = PCT, BOLD
        share = model.freight_share(plan, opt.cost, opt.units)
        if share is not None:
            expected.append(Expected(FREIGHT_SHEET, f"F{r}", share, f"freight share of {opt.name}"))
    widths(ws, {"A": 2, "B": 40, "C": 14, "D": 12, "E": 16, "F": 14})


def write_market(wb: Workbook, plan: Plan) -> None:
    ws = wb.create_sheet(MARKET_OUT_SHEET)
    ws.cell(1, 2, "Market size").font = TITLE
    header_row(ws, 3, MARKET_COLS, start_col=2)
    for i in range(len(plan.market)):
        for j, col in enumerate("ABCD"):
            c = ws.cell(4 + i, 2 + j, f"=IF('{MARKET_SHEET}'!{col}{2 + i}=\"\",\"\",'{MARKET_SHEET}'!{col}{2 + i})")
            c.alignment = WRAP
    widths(ws, {"A": 2, "B": 34, "C": 30, "D": 20, "E": 44})
